
services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: property_management_db
    hostname: sqlserver
    environment:
      ACCEPT_EULA: Y
      SA_PASSWORD: Property123!
      MSSQL_PID: Express
    ports:
      - "1433:1433"
    volumes:
      - sqlserver_data:/var/opt/mssql
    restart: unless-stopped

  web:
    build:
      context: .
      dockerfile: PropertyManagementSystem.Web/Dockerfile
    container_name: property_management_web
    depends_on:
      - sqlserver
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=sqlserver,1433;Database=PropertyManagement;User=sa;Password=Property123!;TrustServerCertificate=true;
    ports:
      - "5213:8080"
    restart: unless-stopped

volumes:
  sqlserver_data:
